### ISSUE TITLE
Unable to make the library work

### ISSUE THREAD

**Issue by ostafen** [Raja0sama/-supersami-react-native-foreground-service#1]
I tried this library. However i was not able to make it work. The documentation is not enough. Please add more detailed instructions

**Comment by Raja0sama** [comment]
What went wrong ?

**Comment by pjc0247** [comment]
@Raja0sama seems not working too,
it only throws error with a message
`Error: ForegroundService: Foreground service failed to start.`

it would be nice to put more details in the message

**Comment by Raja0sama** [comment]
> @Raja0sama seems not working too,
> it only throws an error with a message
> `Error: ForegroundService: Foreground service failed to start.`
> 
> it would be nice to put more details in the message

Well, let me create an example simple app and show you that it works.

**Comment by pjc0247** [comment]
@Raja0sama 

Seems this commit is not published yet, i think thats why
https://github.com/Raja0sama/-supersami-react-native-foreground-service/pull/2

**Comment by Raja0sama** [comment]
I working on new documentation I will be uploading a sample app over GitHub
and updating documentation so you can easily use it.

**Comment by pjc0247** [comment]
@Raja0sama nice, thanks!

**Comment by Raja0sama** [comment]
Hey Read the md file, I re-write the documentation, it is a work in progress. The package name is being changed please use the updated one.

and the link the [Example App](https://github.com/Raja0sama/ForegroundSerivceExample.git)

If you face any issue, kindly post a separate issue with the screenshot and repo link.
